### ISSUE TITLE
1.1.4点击实例后闪退

### ISSUE THREAD

**Issue by keyblues** [icylian/MDPings#9]
版本：1.1.4
环境：鸿蒙next+卓易通

**Comment by icylian** [comment]
请确认下哪吒监控的面板版本，更新到1.1.4再尝试。
如果已经在使用1.1.4，建议尝试抓取并提供错误日志，或者进群提供测试用的账号。

**Comment by webhawk1234** [comment]
同样出现闪退。面板：1.1.6 。手机：harmonyOS4.2

**Comment by jaydong2016** [comment]
同样闪退
java.time.format.DateTimeParseException: Text '2024-12-16T04:02:49.410731615+01:00' could not be parsed at index 29
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2044)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1946)
	at java.time.Instant.parse(Instant.java:389)
	at com.sekusarisu.mdpings.vpings.presentation.models.ServerUiKt.toEpochMilli(ServerUi.kt:198)
	at com.sekusarisu.mdpings.vpings.presentation.models.WSServerUiKt.toWSServerUi(WSServerUi.kt:67)
	at com.sekusarisu.mdpings.vpings.presentation.server_list.ServerListViewModel$loadWSServers$1$3.emit(ServerListViewModel.kt:132)
	at com.sekusarisu.mdpings.vpings.presentation.server_list.ServerListViewModel$loadWSServers$1$3.emit(ServerListViewModel.kt:129)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:51)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:221)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:177)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:149)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:591)
	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:2957)
	at kotlinx.coroutines.channels.BufferedChannelKt.access$tryResume0(BufferedChannel.kt:1)
	at kotlinx.coroutines.channels.BufferedChannel$BufferedChannelIterator.tryResumeHasNext(BufferedChannel.kt:1719)
	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:662)
	at kotlinx.coroutines.channels.BufferedChannel.updateCellSend(BufferedChannel.kt:478)
	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:33)
	at kotlinx.coroutines.channels.BufferedChannel.send$suspendImpl(BufferedChannel.kt:3150)
	at kotlinx.coroutines.channels.BufferedChannel.send(Unknown Source:0)
	at kotlinx.coroutines.channels.ChannelCoroutine.send(Unknown Source:2)
	at com.sekusarisu.mdpings.vpings.data.networking.RemoteRealtimeServerDataClient$getServerListStateStream$2$1.invokeSuspend(RemoteRealtimeServerDataClient.kt:176)
	at com.sekusarisu.mdpings.vpings.data.networking.RemoteRealtimeServerDataClient$getServerListStateStream$2$1.invoke(Unknown Source:8)
	at com.sekusarisu.mdpings.vpings.data.networking.RemoteRealtimeServerDataClient$getServerListStateStream$2$1.invoke(Unknown Source:4)
	at io.ktor.client.plugins.websocket.BuildersKt.webSocket(builders.kt:101)
	at io.ktor.client.plugins.websocket.BuildersKt$webSocket$1.invokeSuspend(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ef00ea7, Dispatchers.Main.immediate]

**Comment by icylian** [comment]
感谢提供日志，今晚发版修复

**Comment by icylian** [comment]
> 同样闪退 java.time.format.DateTimeParseException: Text '2024-12-16T04:02:49.410731615+01:00' could not be parsed at index 29 at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2044) at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1946) at java.time.Instant.parse(Instant.java:389) at com.sekusarisu.mdpings.vpings.presentation.models.ServerUiKt.toEpochMilli(ServerUi.kt:198) at com.sekusarisu.mdpings.vpings.presentation.models.WSServerUiKt.toWSServerUi(WSServerUi.kt:67) at com.sekusarisu.mdpings.vpings.presentation.server_list.ServerListViewModel$loadWSServers$1$3.emit(ServerListViewModel.kt:132) at com.sekusarisu.mdpings.vpings.presentation.server_list.ServerListViewModel$loadWSServers$1$3.emit(ServerListViewModel.kt:129) at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:51) at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33) at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1) at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:221) at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:177) at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:149) at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470) at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:591) at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:2957) at kotlinx.coroutines.channels.BufferedChannelKt.access$tryResume0(BufferedChannel.kt:1) at kotlinx.coroutines.channels.BufferedChannel$BufferedChannelIterator.tryResumeHasNext(BufferedChannel.kt:1719) at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:662) at kotlinx.coroutines.channels.BufferedChannel.updateCellSend(BufferedChannel.kt:478) at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:33) at kotlinx.coroutines.channels.BufferedChannel.send$suspendImpl(BufferedChannel.kt:3150) at kotlinx.coroutines.channels.BufferedChannel.send(Unknown Source:0) at kotlinx.coroutines.channels.ChannelCoroutine.send(Unknown Source:2) at com.sekusarisu.mdpings.vpings.data.networking.RemoteRealtimeServerDataClient$getServerListStateStream$2$1.invokeSuspend(RemoteRealtimeServerDataClient.kt:176) at com.sekusarisu.mdpings.vpings.data.networking.RemoteRealtimeServerDataClient$getServerListStateStream$2$1.invoke(Unknown Source:8) at com.sekusarisu.mdpings.vpings.data.networking.RemoteRealtimeServerDataClient$getServerListStateStream$2$1.invoke(Unknown Source:4) at io.ktor.client.plugins.websocket.BuildersKt.webSocket(builders.kt:101) at io.ktor.client.plugins.websocket.BuildersKt$webSocket$1.invokeSuspend(Unknown Source:13) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:210) at android.os.Looper.loop(Looper.java:299) at android.app.ActivityThread.main(ActivityThread.java:8261) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ef00ea7, Dispatchers.Main.immediate]

已修复，请更新至1.1.5
